import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


//<<<<<<<<<<<<<<<<<<<<<<<<<------------------------------------------ Font Family ------------------------------------------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});


//<<<<<<<<<<<<<<<<<<<<<<<<<------------------------------------------ SEO ------------------------------------------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


//<<<<<<<<<<<<<<<<<<<<<<<<<------------------------------------------ Root Layout ------------------------------------------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${manrope.className} antialiased`}>
        <div className="bg-[#050505]">{children}</div>
      </body>
    </html>
  );
}

